update rockcraft.yaml

diff --git a/airbyte_ui_rock/rockcraft.yaml b/airbyte_ui_rock/rockcraft.yaml
--- a/airbyte_ui_rock/rockcraft.yaml
+++ b/airbyte_ui_rock/rockcraft.yaml
@@ -15,7 +15,7 @@ services:
   nginx:
     override: replace
     summary: "NGINX service to serve Airbyte WebApp"
-    command: "./docker-entrypoint.sh nginx"
+    command: "./docker-entrypoint.sh nginx -c /etc/nginx/nginx.conf"
     startup: enabled
 
 environment:
@@ -25,52 +25,18 @@ environment:
   CDK_VERSION: "5.12.0"
 
 parts:
-#   nginx-user:
-#     plugin: nil
-#     source-type: local
-#     source: .
-#     stage-packages:
-#       - base-passwd
-#       - base-files
-#       - nginx
-#       - bash
-#     override-build: |
-#       craftctl default
-#       groupadd --root ${CRAFT_PART_INSTALL} nginx
-#       useradd -d /home/nginx -s /bin/bash --root ${CRAFT_PART_INSTALL} -g nginx nginx
-
-#       groupadd nginx
-#       useradd -d /home/nginx -s /bin/bash -g nginx nginx
-
-#       rm $CRAFT_PART_INSTALL/etc/nginx/nginx.conf
-#       grep nginx ${CRAFT_PART_INSTALL}/etc/passwd
-#       id -u nginx
-# #    override-prime: |
-# #      craftctl default
-# #      echo "nginx:x:101:101::/home/nginx:/bin/bash" >> ${CRAFT_PRIME}/etc/passwd
-# #      echo "nginx:x:101:" >> ${CRAFT_PRIME}/etc/group
-#     prime:
-#       - etc/passwd
-#       - etc/group
-#       - etc/nginx
-#       - usr/sbin/nginx
-
-  # config:
-  #   plugin: dump
-  #   after:
-  #     - nginx-user
-  #   source: files
-  #   organize:
-  #     nginx.conf: etc/nginx/nginx.conf
-  #     default.conf: etc/nginx/conf.d/default.conf
-  #   stage:
-  #     - etc/nginx/nginx.conf
-  #     - etc/nginx/conf.d/default.conf
+  config:
+    plugin: dump
+    source: files
+    organize:
+      nginx.conf: etc/nginx/nginx.conf
+      default.conf: etc/nginx/conf.d/default.conf
+    stage:
+      - etc/nginx/nginx.conf
+      - etc/nginx/conf.d/default.conf
 
   patches:
     plugin: dump
-    # after:
-      # - config
     source: ./patches
     organize:
       vite-config-http.patch: patches/vite-config-http.patch
@@ -80,9 +46,9 @@ parts:
       - "-*"
 
   pull-airbyte-repo:
-    after: [patches]
+    after: [patches, config]
     plugin: dump
-    source: https://github.com/airbytehq/airbyte-platform.git # yamllint disable-line
+    source: https://github.com/airbytehq/airbyte-platform.git
     source-type: git
     source-tag: v1.4.0
     build-packages:
@@ -128,22 +94,16 @@ parts:
       - base-passwd
       - base-files
       - nginx
-      - bash
     override-build: |
       craftctl default
+
       groupadd --root ${CRAFT_PART_INSTALL} nginx
       useradd -d /home/nginx -s /bin/bash --root ${CRAFT_PART_INSTALL} -g nginx nginx
 
       groupadd nginx
       useradd -d /home/nginx -s /bin/bash -g nginx nginx
 
-      rm $CRAFT_PART_INSTALL/etc/nginx/nginx.conf
-      grep nginx ${CRAFT_PART_INSTALL}/etc/passwd
-      id -u nginx
-
-      GID=584792
-
-      NGINX_UID=$(id -u nginx)
+      grep nginx ${CRAFT_PART_INSTALL}/etc/passwd || echo "nginx user not found in passwd"
 
       git apply ${CRAFT_STAGE}/patches/*.patch
 
@@ -152,66 +112,40 @@ parts:
 
       cp -r . ${CRAFT_PART_INSTALL}/airbyte-platform
 
-      mkdir ${CRAFT_PART_INSTALL}/docker-entrypoint.d
+      mkdir -p ${CRAFT_PART_INSTALL}/docker-entrypoint.d
       mkdir -p ${CRAFT_PART_INSTALL}/etc/nginx/templates
       mkdir -p ${CRAFT_PART_INSTALL}/etc/nginx/conf.d
       mkdir -p ${CRAFT_PART_INSTALL}/usr/share/nginx/html
-      mkdir -p /var/cache/nginx
+      mkdir -p ${CRAFT_PART_INSTALL}/var/cache/nginx
 
-      cp -r ./docker/airbyte-nginx/alpine-slim/10-listen-on-ipv6-by-default.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
-      cp -r ./docker/airbyte-nginx/alpine-slim/15-local-resolvers.envsh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/15-local-resolvers.envsh
-      cp -r ./docker/airbyte-nginx/alpine-slim/20-envsubst-on-templates.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/20-envsubst-on-templates.sh
-      cp -r ./docker/airbyte-nginx/alpine-slim/30-tune-worker-processes.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/30-tune-worker-processes.sh
-      cp -r ./docker/airbyte-nginx/alpine-slim/docker-entrypoint.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.sh
+      cp -r ./docker/airbyte-nginx/alpine-slim/10-listen-on-ipv6-by-default.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/
+      cp -r ./docker/airbyte-nginx/alpine-slim/15-local-resolvers.envsh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/
+      cp -r ./docker/airbyte-nginx/alpine-slim/20-envsubst-on-templates.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/
+      cp -r ./docker/airbyte-nginx/alpine-slim/30-tune-worker-processes.sh ${CRAFT_PART_INSTALL}/docker-entrypoint.d/
+      cp -r ./docker/airbyte-nginx/alpine-slim/docker-entrypoint.sh ${CRAFT_PART_INSTALL}/
 
       cp -r ./airbyte-webapp/nginx/default.conf.template ${CRAFT_PART_INSTALL}/etc/nginx/templates
       cp -r ./airbyte-webapp/build/airbyte/docker/bin/build ${CRAFT_PART_INSTALL}/usr/share/nginx/html
-      
-      # Ensure default.conf exists before modifying it
-      if [ ! -f /etc/nginx/conf.d/default.conf ]; then
-          echo "Creating default.conf..."
-          cat <<EOF > /etc/nginx/conf.d/default.conf
-      server {
-          listen 80;
-          server_name localhost;
-          location / {
-              root /usr/share/nginx/html;
-              index index.html;
-          }
-      }
-      EOF
-      fi
 
-      sed -i 's,listen       80;,listen       8080;,' /etc/nginx/conf.d/default.conf
-      sed -i 's,/var/run/nginx.pid,/tmp/nginx.pid,' /etc/nginx/nginx.conf
-      sed -i "/^http {/a \    proxy_temp_path /tmp/proxy_temp;\n    client_body_temp_path /tmp/client_temp;\n    fastcgi_temp_path /tmp/fastcgi_temp;\n    uwsgi_temp_path /tmp/uwsgi_temp;\n    scgi_temp_path /tmp/scgi_temp;\n" /etc/nginx/nginx.conf
-      # nginx user must own the cache and etc directory to write cache and tweak the nginx config
-      chown -R $NGINX_UID:nginx /var/cache/nginx
-      chmod -R g+w /var/cache/nginx
-      chown -R $NGINX_UID:nginx /etc/nginx
-      chmod -R g+w /etc/nginx
+      # Update nginx configuration files (inside the install tree)
+      sed -i 's,listen       80;,listen       8080;,' ${CRAFT_PART_INSTALL}/etc/nginx/conf.d/default.conf
+      sed -i 's,/var/run/nginx.pid,/tmp/nginx.pid,' ${CRAFT_PART_INSTALL}/etc/nginx/nginx.conf
+      sed -i "/^http {/a \    proxy_temp_path /tmp/proxy_temp;\n    client_body_temp_path /tmp/client_temp;\n    fastcgi_temp_path /tmp/fastcgi_temp;\n    uwsgi_temp_path /tmp/uwsgi_temp;\n    scgi_temp_path /tmp/scgi_temp;\n" ${CRAFT_PART_INSTALL}/etc/nginx/nginx.conf
 
-      which envsubst
-      which nginx
+      # Set permissions
+      chown -R $(id -u nginx):nginx ${CRAFT_PART_INSTALL}/var/cache/nginx
+      chmod -R g+w ${CRAFT_PART_INSTALL}/var/cache/nginx
+      chown -R $(id -u nginx):nginx ${CRAFT_PART_INSTALL}/etc/nginx
+      chmod -R g+w ${CRAFT_PART_INSTALL}/etc/nginx
 
-      cp -r /usr/bin/envsubst ${CRAFT_PART_INSTALL}/envsubst
-      cp -r /usr/sbin/nginx ${CRAFT_PART_INSTALL}/nginx
-    organize:
-      envsubst: bin/envsubst
-      nginx: sbin/nginx
+      # Copy binaries
+      cp -r /usr/bin/envsubst ${CRAFT_PART_INSTALL}/bin/envsubst
+      cp -r /usr/sbin/nginx ${CRAFT_PART_INSTALL}/sbin/nginx
     stage:
-      - etc/passwd
-      - etc/group
       - etc/nginx
-      - sbin/nginx
-      # - nginx
-      # - etc/nginx/templates/default.conf.template
+      - var/cache/nginx
       - usr/share/nginx/html
       - docker-entrypoint.sh
       - docker-entrypoint.d
       - bin/envsubst
-    # prime:
-    #   - etc/passwd
-    #   - etc/group
-    #   - etc/nginx
-      # - usr/sbin/nginx
+      - sbin/nginx
